model:
  vocab_size: 
  d_model: 
  d_intermediate: 
  n_layer: 
  fsdp_layer_wrap: 
  activation_checkpointing: 
  ssm_cfg_layer:

data:
  global_batch_size: 
  micro_batch_size: 
  eval_batch_size: 
  seq_len: 
  num_workers: 
  prefetch_factor: 
  n_total_tokens:
  n_samples_to_skip: 
  token_size: 
  text_paths:
  - path:

optimizer:
  lr: 
  beta1: 
  beta2: 
  weight_decay:

scheduler:
  name: 
  t_warmup: 
  t_max:
  t_decay: 
  alpha_f:

fsdp:
  sharding_strategy: 
  process_group: 
  backward_prefetch: 
  activation_checkpointing_reentrant: 
  activation_checkpointing:
  limit_all_gathers: 
  verbose:

trainer:
  cp_interval: 
  eval_interval: 
  save_interval: 
  eval_subset_num_batches: 
  save_folder: 
  save_num_checkpoints_to_keep: 
  auto_log_hparams: 
  autoresume:

general:
  project_name:
  full_name:
  window_size: 
  clipping_threshold: